version: '2'
networks:
  urllc:
    external: false
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    networks:
      - urllc
    depends_on:
      - db
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
  db:
      image: mysql:5.7
      networks:
        - urllc
#      ports:
#        - "3336:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: urllc
      volumes:
        - "./database:/var/lib/mysql"